(def icons ["MoonIcon" "BoltSlashIcon" "ClipboardDocumentListIcon" "ArrowRightIcon"
            "BellSnoozeIcon" "BuildingOffice2Icon" "InboxIcon" "Bars3Icon"
            "ArrowsPointingInIcon" "ReceiptRefundIcon" "ArrowDownRightIcon"
            "ArrowUpTrayIcon" "ArchiveBoxArrowDownIcon" "MagnifyingGlassCircleIcon"
            "RectangleStackIcon" "ChartBarSquareIcon" "KeyIcon" "MusicalNoteIcon"
            "ArrowPathRoundedSquareIcon" "ChevronLeftIcon" "ClipboardDocumentIcon"
            "ArrowLongRightIcon" "BuildingOfficeIcon" "GlobeAmericasIcon"
            "ArrowUturnUpIcon" "WindowIcon" "ArrowSmallLeftIcon" "Cog8ToothIcon"
            "EllipsisHorizontalIcon" "CalendarDaysIcon" "UserMinusIcon"
            "CloudArrowDownIcon" "ArrowsPointingOutIcon" "CheckBadgeIcon" "MapPinIcon"
            "FunnelIcon" "Bars3BottomLeftIcon" "Square2StackIcon" "CalculatorIcon"
            "ArrowDownLeftIcon" "MinusIcon" "ArrowRightOnRectangleIcon" "TableCellsIcon"
            "TrashIcon" "ChatBubbleOvalLeftIcon" "VariableIcon" "WrenchIcon"
            "ArrowLongDownIcon" "BackwardIcon" "GlobeEuropeAfricaIcon" "RadioIcon"
            "ExclamationCircleIcon" "SwatchIcon" "ShoppingBagIcon" "PaperAirplaneIcon"
            "ArrowUturnDownIcon" "BackspaceIcon" "XMarkIcon" "QueueListIcon"
            "ArrowUpOnSquareStackIcon" "CurrencyPoundIcon" "ListBulletIcon"
            "CurrencyDollarIcon" "AcademicCapIcon" "EnvelopeIcon" "CameraIcon" "EyeIcon"
            "InboxStackIcon" "PlayIcon" "CurrencyYenIcon" "ChatBubbleBottomCenterTextIcon"
            "ArrowUpRightIcon" "MinusSmallIcon" "ChatBubbleLeftEllipsisIcon"
            "BarsArrowUpIcon" "UsersIcon" "GiftTopIcon" "FlagIcon" "DocumentArrowDownIcon"
            "FolderOpenIcon" "BookmarkSlashIcon" "StopIcon" "BarsArrowDownIcon"
            "CurrencyBangladeshiIcon" "ArrowSmallDownIcon" "ShieldCheckIcon" "TrophyIcon"
            "VideoCameraIcon" "RectangleGroupIcon" "UserPlusIcon" "ScissorsIcon"
            "CloudArrowUpIcon" "BuildingStorefrontIcon" "PaperClipIcon" "ArrowSmallUpIcon"
            "BoltIcon" "ChevronRightIcon" "FolderIcon" "CodeBracketIcon"
            "ReceiptPercentIcon" "ArrowTrendingDownIcon" "ArrowsUpDownIcon" "PlusIcon"
            "ChatBubbleLeftRightIcon" "BugAntIcon" "EllipsisHorizontalCircleIcon"
            "MagnifyingGlassIcon" "NewspaperIcon" "ArrowDownIcon" "RssIcon" "ClipboardIcon"
            "LifebuoyIcon" "ChevronDoubleRightIcon" "TvIcon" "DocumentDuplicateIcon"
            "EyeSlashIcon" "ServerIcon" "HomeIcon" "ServerStackIcon" "EyeDropperIcon"
            "QuestionMarkCircleIcon" "BriefcaseIcon" "ArchiveBoxXMarkIcon" "PlayCircleIcon"
            "BookOpenIcon" "GlobeAltIcon" "IdentificationIcon" "CodeBracketSquareIcon"
            "FolderArrowDownIcon" "CloudIcon" "TicketIcon" "VideoCameraSlashIcon"
            "ExclamationTriangleIcon" "CurrencyEuroIcon" "CheckIcon" "Bars2Icon"
            "SignalSlashIcon" "Cog6ToothIcon" "ChevronDoubleLeftIcon" "WifiIcon"
            "PencilSquareIcon" "CurrencyRupeeIcon" "PowerIcon" "QrCodeIcon" "Battery50Icon"
            "HomeModernIcon" "BuildingLibraryIcon" "HandThumbDownIcon"
            "ChatBubbleBottomCenterIcon" "Bars3BottomRightIcon" "SquaresPlusIcon"
            "Squares2X2Icon" "LightBulbIcon" "DocumentTextIcon" "PhotoIcon"
            "DocumentArrowUpIcon" "ArrowUpOnSquareIcon" "CubeTransparentIcon"
            "ArrowRightCircleIcon" "GifIcon" "PauseIcon" "TagIcon" "ArrowUpCircleIcon"
            "ArrowDownOnSquareIcon" "FireIcon" "LanguageIcon" "CircleStackIcon"
            "AdjustmentsHorizontalIcon" "DocumentMagnifyingGlassIcon" "PhoneXMarkIcon"
            "WalletIcon" "BookmarkIcon" "MinusCircleIcon" "BanknotesIcon" "ChevronUpIcon"
            "ShieldExclamationIcon" "BellAlertIcon" "PlusSmallIcon" "CpuChipIcon"
            "HashtagIcon" "PuzzlePieceIcon" "BeakerIcon" "DocumentCheckIcon"
            "CursorArrowRippleIcon" "CheckCircleIcon" "PaintBrushIcon"
            "Bars3CenterLeftIcon" "SignalIcon" "ForwardIcon" "WrenchScrewdriverIcon"
            "DocumentIcon" "ChatBubbleLeftIcon" "ChevronDoubleDownIcon"
            "MagnifyingGlassPlusIcon" "ArrowLeftIcon" "ArrowDownCircleIcon" "ChartBarIcon"
            "LinkIcon" "ChatBubbleOvalLeftEllipsisIcon" "HandRaisedIcon"
            "ArrowUturnRightIcon" "SpeakerXMarkIcon" "ArrowDownOnSquareStackIcon"
            "ArrowUpIcon" "LockClosedIcon" "DocumentChartBarIcon" "UserGroupIcon"
            "GlobeAsiaAustraliaIcon" "PlayPauseIcon" "PhoneArrowDownLeftIcon" "ScaleIcon"
            "DocumentPlusIcon" "FaceSmileIcon" "NoSymbolIcon" "ChartPieIcon"
            "ViewColumnsIcon" "RocketLaunchIcon" "MapIcon" "PauseCircleIcon" "AtSymbolIcon"
            "ArrowLeftCircleIcon" "TruckIcon" "Battery0Icon" "ArrowsRightLeftIcon"
            "SunIcon" "DocumentMinusIcon" "SpeakerWaveIcon" "SparklesIcon" "CakeIcon"
            "ShoppingCartIcon" "EnvelopeOpenIcon" "ArrowTopRightOnSquareIcon"
            "FolderMinusIcon" "ArrowSmallRightIcon" "FolderPlusIcon"
            "PresentationChartBarIcon" "ChevronUpDownIcon" "MegaphoneIcon" "GiftIcon"
            "ClipboardDocumentCheckIcon" "CalendarIcon" "ClockIcon" "InformationCircleIcon"
            "ArrowTrendingUpIcon" "ArrowLongUpIcon" "MicrophoneIcon"
            "MagnifyingGlassMinusIcon" "ArrowLeftOnRectangleIcon" "ArrowUpLeftIcon"
            "FilmIcon" "PrinterIcon" "ChevronDownIcon" "PencilIcon" "LockOpenIcon"
            "Bars4Icon" "ShareIcon" "EllipsisVerticalIcon" "StarIcon" "Square3Stack3DIcon"
            "FingerPrintIcon" "UserCircleIcon" "HeartIcon" "UserIcon" "XCircleIcon"
            "ArrowPathIcon" "FaceFrownIcon" "BellSlashIcon" "AdjustmentsVerticalIcon"
            "ArrowLongLeftIcon" "CogIcon" "DeviceTabletIcon" "CommandLineIcon"
            "ArrowUturnLeftIcon" "ChevronDoubleUpIcon" "BookmarkSquareIcon"
            "ComputerDesktopIcon" "BellIcon" "ArrowDownTrayIcon" "CubeIcon"
            "PresentationChartLineIcon" "ArchiveBoxIcon" "PhoneIcon" "ViewfinderCircleIcon"
            "Battery100Icon" "CreditCardIcon" "PhoneArrowUpRightIcon" "CursorArrowRaysIcon"
            "DevicePhoneMobileIcon" "StopCircleIcon" "InboxArrowDownIcon" "HandThumbUpIcon"
            "PlusCircleIcon"])